version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
         soft: -1
         hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx3g -Xms3g"
      cluster.name: "chicago-crime-analytics"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
 #   environment:
 #     SERVER_NAME: code.janitor.org
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

#     - elk
  # logstash:
  #   build: logstash/
  #   volumes:
  #     - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
  #     - ./logstash/pipeline:/usr/share/logstash/pipeline
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx1024m -Xms1024m"
  #   networks:
  #     - elk
  #   depends_on:
  #     - elasticsearch