version: '3'

services:
  neo4j:
    image: neo4j:3.5.1
    network_mode: "bridge"
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    environment:
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_active__database=chicago.crime.db
      - NEO4J_dbms_shell_enabled=true
      - NEO4J_dbms_memory_pagecache_size=3G
      - NEO4J_dbms_memory_heap_initial__size=2G
      - NEO4J_AUTH=none
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_tx__log_rotation_retention__policy=1G size
    volumes:
      - ./neo4j/plugins:/plugins
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/conf/:/conf/  